## Github Actions CI workflow to build and release Flutter Android APK
name: Build and Release

on:
  # Run this workflow when a new tag is pushed
  push:
    tags:
      - 'v*'

jobs:
  build_android:
    # Only run this job if the branch name starts with 'release/'
    name: Build Android
    runs-on: ubuntu-latest
    env:
      # Setup env variables that will be used throughout the workflow
      JAVA_VERSION: 17.0
      FLUTTER_VERSION: 3.24.3
      AAB_PATH: build/app/outputs/bundle/release/app-release.aab
    steps:
      # Checkout repository codebase
      - name: Checkout the code
        uses: actions/checkout@v4

      # Setup Java in the VM
      - name: Setup Java to compile the Android project
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}

      # Setup Flutter in the VM
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      # Run flutter commands
      - name: 📦 Install dependencies
        run: flutter pub get

      - name: 🕵️ Analyze to check for bad Dart/Flutter practices
        run: flutter analyze

      - name: 📉 Run all app tests
        run: flutter test

      # Build Android APK release file
      - name: Build apk
        run: |
          flutter build apk \
            --release \
            --build-number=${{ github.run_number }} \
            --build-name=${{ github.ref }}

      - name: Upload built apk
        uses: actions/upload-artifact@v4
        with:
          path: build/app/outputs/flutter-apk/app-release.apk

  release:
    name: Release
    needs: build_android
    runs-on: ubuntu-latest
    steps:
      - name: Download built apk
        uses: actions/download-artifact@v2
        with:
          path: app.apk


      - uses: ncipollo/release-action@v1
        with:
          artifacts: app.apk
          artifactContentType: application/vnd.android.package-archive
          generateReleaseNotes: true
